import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import ReduxStoreProvider from "@/components/ReduxStoreProvider";
import { ImageKitProvider } from "@imagekit/next";
import ToastProvider from "@/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const urlEndpoint = process.env.IMAGEKIT_URL_ENDPOINT as string;
const PayPalClientId = process.env.PAYPAL_CLIENT_ID as string;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-clip`}
      >
        <ImageKitProvider urlEndpoint={urlEndpoint}>
          <ReduxStoreProvider>
            <ToastProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </ToastProvider>
          </ReduxStoreProvider>
        </ImageKitProvider>
      </body>
    </html>
  );
}
